/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as mutations from "../mutations";
import type * as queries from "../queries";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about what functions are available and their
 * arguments and return types.
 *
 * This type should be used with type-parameterized classes like `ConvexReactClient`
 * to create app-specific types.
 */
export type API = ApiFromModules<{
  mutations: typeof mutations;
  queries: typeof queries;
}>;

export declare const api: API;
